aws-cloudformation/cloudformation-cli-typescript-plugin

- README.md
- package-lock.json
- package.json
- src/resource.ts
- tests/lib/resource.test.ts
While trying to access the instance with `this` in an event handler method, the following error was being thrown:
>TypeError: Cannot read property 'typeName' of undefined
The change here fix the issue by binding the instance to the method.
> Fix event handler binding issue

- package-lock.json
- package.json
- python/rpdk/typescript/codegen.py
- python/rpdk/typescript/templates/README.md
- python/rpdk/typescript/templates/handlers.ts
- src/callback.ts
- src/log-delivery.ts
- src/resource.ts
- src/utils.ts
- tests/lib/log-delivery.test.ts
Fixes #10 and improves error logging to help investigate underlying service issues.
> Improve error logging

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- .pylintrc
- Pipfile.lock
- python/rpdk/typescript/codegen.py
- python/rpdk/typescript/data/typescript.gitignore
- python/rpdk/typescript/resolver.py
- python/rpdk/typescript/templates/models.ts
- setup.py
- src/callback.ts
- src/interface.ts
- src/proxy.ts
- src/resource.ts
- src/utils.ts
- tests/lib/callback.test.ts
- tests/lib/interface.test.ts
- tests/lib/proxy.test.ts
- tests/lib/resource.test.ts
- tests/plugin/resolver_test.py
Update with changes so it is in sync with other Cloudformation CLI plugins.
> Update with changes from other plugins

- jest.config.js
- src/resource.ts
- src/utils.ts
- tests/lib/resource.test.ts
*Issue #, if available:* #15 
This is will properly format the callback context even from different types (array, object literal or Map) that were serialized.
> format callback context properly

- python/rpdk/typescript/data/create.json
- python/rpdk/typescript/templates/README.md
- python/rpdk/typescript/templates/package.json
- src/recast.ts
- tests/lib/recast.test.ts
*Issue #, if available:* #12 
*Description of changes:* This will cast to a number or boolean considering the case where an empty string is sent by CloudFormation.
> Fix casting from empty string to number or boolean

- src/interface.ts
- src/proxy.ts
- src/resource.ts
- tests/lib/interface.test.ts
- tests/lib/resource.test.ts
Additional properties to `BaseResourceHandlerRequest` class:
* desiredResourceTags
* previousResourceTags
* systemTags
* awsAccountId
* region
* awsPartition
> Add new properties for resource request

- package.json
- python/rpdk/typescript/templates/README.md
- python/rpdk/typescript/templates/handlers.ts
- src/exceptions.ts
- src/log-delivery.ts
- src/metrics.ts
- src/resource.ts
- tests/data/sample-model.ts
- tests/lib/interface.test.ts
- tests/lib/log-delivery.test.ts
- tests/lib/proxy.test.ts
- tests/lib/recast.test.ts
- tests/lib/resource.test.ts
Increase [default options for util inspect](https://github.com/nodejs/node/pull/8013) so that deep objects are also printed. It also exposes the model type reference in the resource class.
> Increase default util inspect depth for objects

- setup.py
`cloudformation-cli` versions older than [`0.1.11`](https://github.com/aws-cloudformation/cloudformation-cli/releases/tag/v0.1.11) are being deprecated
> feat: upgrading minimum cloudformation-cli version

- .github/workflows/ci.yml
> build: cfn init command failing

- setup.py
introduced in https://github.com/aws-cloudformation/cloudformation-cli-typescript-plugin/pull/43, but `docker` is already an indirect dependency from `cloudformation-cli`, so this was just pinning `docker` version stricter than `cloudformation-cli`, which causes issues
https://github.com/aws-cloudformation/cloudformation-cli/issues/727
> removing explicit docker pinning

- .gitignore
- .pre-commit-config.yaml
- README.md
- python/rpdk/typescript/codegen.py
- python/rpdk/typescript/templates/handlers.ts
- src/exceptions.ts
- src/interface.ts
- src/resource.ts
- tests/lib/resource.test.ts
This pull request adds type configuration support to cfn resources generated by the cli using the typescript plugin.  This matches the same functionality in the java cli plugin.
> Add type configuration support to the typescript cli plugin

- src/resource.ts
Closes #65 
Switch out console.debug for this.log in src/resource.ts/waitRunningProcess()
> fix(log): Switch from console.debug to this.log in resource.ts

- .github/workflows/ci.yml
Closes #85 
Run CI testing on MacOS to help ensure no breaking changes.
> feat(CI): add MacOS CI testing

- .github/workflows/ci.yml
- python/rpdk/typescript/codegen.py
- python/rpdk/typescript/parser.py
- tests/plugin/codegen_test.py
- tests/plugin/parser_test.py
Closes #89 
Add in no-docker CLI switch command to correspond with the opposite use-docker CLI switch.
> feat(cli): no-docker CLI switch

- src/recast.ts
- tests/data/sample-model.ts
- tests/lib/recast.test.ts
*Issue #, if available:* #97
Whenever defining an array with unique items in the resource, we will ensure those are serialized correctly instead of throwing an error.
> fix: unable to serialize array with unique items

- python/rpdk/typescript/__init__.py
> Tooling(v1.0.2) version bump

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Closes #107 
github runner for ubuntu 18.04 was deprecated and GHA workflows were stuck.  This updates workflows to use latest ubuntu runners.
> update GHA runners to ubuntu latest

- python/rpdk/typescript/codegen.py
Closes #105 
Update typescript templates to use NodeJS 18.
> Update nodejs in templates to 18

- src/resource.ts
- tests/lib/resource.test.ts
> Stop logging event data

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .pre-commit-config.yaml
- Pipfile.lock
- package-lock.json
- package.json
- python/rpdk/typescript/codegen.py
- python/rpdk/typescript/templates/Makefile
- python/rpdk/typescript/templates/package.json
- python/rpdk/typescript/templates/template.yml
- setup.py
- tests/plugin/codegen_test.py
#121 
- Add support for nodejs 20
> Add support for nodejs 20

- .github/workflows/ci.yml
- package.json
- python/rpdk/typescript/__init__.py
126
Bump version to release changes for supporting nodejs20 runtime and fix class transformer version incompatibility. 
> Runtime(v1.0.6) + Tooling(v1.0.4) version bump
